version: '3'
services:
  app:
    image: nestjs/user-api:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      - IS_DOCKER=true
    ports:
      - 3001:3001
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev